[package]
name = "auto-gakumasu"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
color-print = "0.3.7"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
